Create repo and export component
selsa-inube/inubekit-datefield pull request #1
Opened 2024-03-04 22:32 UTC by cmarin001

This pull request announces the creation of a new repository for the `<Datefield />` component and its subsequent exportation for use across our application. Aimed at centralizing the development and maintenance of this critical date input component, the repository will serve as the primary source for the latest versions, ensuring consistent functionality and design integration within our digital ecosystem.

2024-03-05 10:36 UTC, JanuarAsprilla commented on package.json
>      "react": "^18.2.0",
should be in peerDependences

2024-03-05 13:51 UTC, cmarin001 commented on package.json
>      "react": "^18.2.0",
solved

2024-03-05 16:13 UTC, JanuarAsprilla approved these changes

2024-03-11 16:21 UTC, wfercanas requested changes

2024-03-11 18:01 UTC, cmarin001 commented on src/Datefield/index.tsx
> +            (Requerido)
solved

2024-03-11 18:01 UTC, cmarin001 commented on vite.config.ts
> +    rollupOptions: {
solved

2024-03-11 18:02 UTC, cmarin001 commented on src/Datefield/index.tsx
> +      {status === "invalid" && !disabled && (
solved

2024-03-11 18:02 UTC, cmarin001 commented on src/Datefield/index.tsx
> +            {message && `${message}`}
solved

2024-03-11 18:02 UTC, cmarin001 commented on src/Datefield/index.tsx
> +      onFocus(e);
solved

2024-03-11 18:28 UTC, cmarin001 commented on src/Datefield/styles.js
> +  $readOnly && inube.label.content.color.regular;
solved

2024-03-11 18:29 UTC, cmarin001 commented on src/Datefield/styles.js
> +  background-color: ${$setBackgroundColor};
solved

2024-03-11 18:29 UTC, cmarin001 commented on src/Datefield/styles.js
> +  grid-template-columns: ${({ $iconBefore, $iconAfter }) => {
solved

2024-03-11 19:31 UTC, cmarin001 commented on src/Datefield/styles.js
solved

2024-03-11 19:36 UTC, cmarin001 commented on src/Datefield/index.tsx
> +        <StyledMessageContainer $disabled={disabled} $status={status}>
solved

2024-03-11 19:57 UTC, cmarin001 commented on src/Datefield/index.tsx
> +        <StyledInput
solved

2024-03-11 20:39 UTC, cmarin001 commented on src/Datefield/index.tsx
> +    <StyledContainer $fullwidth={fullwidth} $disabled={disabled} $size={size}>
solved

2024-03-11 23:00 UTC, JanuarAsprilla approved these changes

2024-03-14 14:46 UTC, wfercanas requested changes

2024-03-14 14:46 UTC, wfercanas commented on src/Datefield/styles.js
> +  background-color:;
This property is empty.

2024-03-14 14:46 UTC, wfercanas commented on src/Datefield/styles.js
Component breaks when fullwidth is true:
![image](https://github.com/selsa-inube/inubekit-datefield/assets/36939686/d098466b-7592-48aa-afc5-ffcfc53b6f61)

2024-03-14 17:22 UTC, cmarin001 commented on src/Datefield/styles.js
> +  background-color:;
solved

2024-03-14 17:30 UTC, cmarin001 commented on src/Datefield/styles.js
solved

2024-03-14 18:57 UTC, wfercanas requested changes

2024-03-14 19:02 UTC, cmarin001 commented on src/Datefield/styles.js
> +    inube.input.message.color.regular}};
solved

2024-03-15 14:28 UTC, wfercanas approved these changes

2024-03-15 14:29 UTC, merged